server:
  port: 801
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunset?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sunset
    password: sunset
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 50MB # 图片上传的大小
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sunset.entity
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
springdoc:
  swagger-ui:
    path: /api
    enabled: true # 开启swagger
  api-docs:
    path: /v1
    enabled: true
  packages-to-scan: com.sunset.controller

