server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://www.dillonl.com:3306/sunset?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sunset
    password: sunset
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  mapper-locations: com.example.sunset.mapper/*.xml
  type-aliases-package: com.example.sunset.entity