server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunset?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: sunset
    password: sunset
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sunset.entity
springdoc:
  swagger-ui:
    path: /
    enabled: true
  api-docs:
    path: /v1
    enabled: true
  packages-to-scan: com.sunset.controller
  paths-to-match: /sign/**,/admin/**